### ISSUE TITLE
ERR no target lines on leaveing instance 

### ISSUE THREAD

**Issue by PandaCakes12321** [Drahsid/TargetLines#4]
like title says upon leaveing some instances theres a issue where the plugin will error out and spam the xllog with the same error.  image attached and also text form.   only way to resolve it is too  disable and re enable

16:43:07.381 ERR Exception during raise of "Void OnDraw()"
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at TargetLines.TargetLine. DrawFancyLine() in /work/repo/TargetLines/TargetLine.cs:line 176
at TargetLines.TargetLine.Draw() in /work/repo/TargetLines/TargetLine.cs:line 847
at TargetLines.Plugin. DrawOverlay() in /work/repo/TargetLines/Plugin.cs:line 224
at TargetLines.ImGuiUtils.WrapBegin(String name, ImGuiWindowFlags flags, Action fn) in /work/repo/TargetLines/ImGuiUtils.cs:line 16
at TargetLines.Plugin. OnDraw() in /work/repo/TargetLines/Plugin.cs:line 259
at Dalamud. Utility. EventHandlerExtensions. HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\\Utility\EventHandlerExtensions.cs:line 124

![310b5128e48331b7aa79aac5d74db487](https://github.com/user-attachments/assets/60fc1784-f28d-4cdf-8f71-495561c936eb)

**Comment by Drahsid** [comment]
To fix this, ensure your minimum sample count is no less than 3, and your maximum sample count is some greater number that is at least 5, or disable dynamic sample count.
Besides that, I have already fixed this issue on my end, so this error will be impossible come the next update.
